2021-10-02 15:52:46,848 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-02 15:52:46,849 - werkzeug - INFO -  * Running on http://10.104.51.226:9000/ (Press CTRL+C to quit)
2021-10-02 15:53:52,357 - job_service_app - INFO - JSON Request: {'clientname': 'Dina', 'jobprofile': 'qwe', 'jobrequirements': 'df'}
2021-10-02 15:53:52,357 - job_service_app - INFO - clientname: Dina
2021-10-02 15:53:52,357 - job_service_app - INFO - Going to call add job API...
2021-10-02 15:53:52,357 - job_service - INFO - In Add Job API
2021-10-02 15:53:52,357 - job_service - INFO - clientname Dina jobprofile qwe jobrequirements df
2021-10-02 15:53:52,357 - job_service_app - ERROR - Exception on /jobservice/addjob [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-job-service/job_service_app.py", line 31, in add_candidate
    jobAdded =  job_service.addJob(clientname=clientname, jobprofile=jobprofile, jobrequirements=jobrequirements)
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-job-service/job_service.py", line 23, in addJob
    job_dao.addjobDAO(clientname, jobprofile, jobrequirements)
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-job-service/job_dao.py", line 40, in addjobDAO
    jobid = random.randint()
TypeError: randint() missing 2 required positional arguments: 'a' and 'b'
2021-10-02 15:53:52,362 - werkzeug - INFO - 127.0.0.1 - - [02/Oct/2021 15:53:52] "[35m[1mPOST /jobservice/addjob HTTP/1.1[0m" 500 -
2021-10-02 15:55:37,184 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-02 15:55:37,185 - werkzeug - INFO -  * Running on http://10.104.51.226:9000/ (Press CTRL+C to quit)
2021-10-02 15:56:06,582 - job_service_app - INFO - JSON Request: {'clientname': 'Dina', 'jobprofile': 'Staff2', 'jobrequirements': 'Java Cloud'}
2021-10-02 15:56:06,582 - job_service_app - INFO - clientname: Dina
2021-10-02 15:56:06,582 - job_service_app - INFO - Going to call add job API...
2021-10-02 15:56:06,582 - job_service - INFO - In Add Job API
2021-10-02 15:56:06,582 - job_service - INFO - clientname Dina jobprofile Staff2 jobrequirements Java Cloud
2021-10-02 15:56:06,583 - job_service_app - ERROR - Exception on /jobservice/addjob [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-job-service/job_service_app.py", line 31, in add_candidate
    jobAdded =  job_service.addJob(clientname=clientname, jobprofile=jobprofile, jobrequirements=jobrequirements)
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-job-service/job_service.py", line 23, in addJob
    job_dao.addjobDAO(clientname, jobprofile, jobrequirements)
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-job-service/job_dao.py", line 47, in addjobDAO
    cursor.execute(mySql_Add_Job_insert_Query)
NameError: name 'cursor' is not defined
2021-10-02 15:56:06,586 - werkzeug - INFO - 127.0.0.1 - - [02/Oct/2021 15:56:06] "[35m[1mPOST /jobservice/addjob HTTP/1.1[0m" 500 -
2021-10-02 16:00:10,689 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-02 16:00:10,690 - werkzeug - INFO -  * Running on http://10.104.51.226:9000/ (Press CTRL+C to quit)
2021-10-02 16:00:27,734 - job_service_app - INFO - JSON Request: {'clientname': 'Dina', 'jobprofile': 'Staff2', 'jobrequirements': 'Java cloud'}
2021-10-02 16:00:27,734 - job_service_app - INFO - clientname: Dina
2021-10-02 16:00:27,734 - job_service_app - INFO - Going to call add job API...
2021-10-02 16:00:27,734 - job_service - INFO - In Add Job API
2021-10-02 16:00:27,734 - job_service - INFO - clientname Dina jobprofile Staff2 jobrequirements Java cloud
2021-10-02 16:00:27,734 - job_service_app - ERROR - Exception on /jobservice/addjob [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-job-service/job_service_app.py", line 31, in add_candidate
    jobAdded =  job_service.addJob(clientname=clientname, jobprofile=jobprofile, jobrequirements=jobrequirements)
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-job-service/job_service.py", line 23, in addJob
    job_dao.addjobDAO(clientname, jobprofile, jobrequirements)
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-job-service/job_dao.py", line 48, in addjobDAO
    cursor.execute(mySql_Add_Job_insert_Query)
AttributeError: 'str' object has no attribute 'execute'
2021-10-02 16:00:27,738 - werkzeug - INFO - 127.0.0.1 - - [02/Oct/2021 16:00:27] "[35m[1mPOST /jobservice/addjob HTTP/1.1[0m" 500 -
2021-10-02 16:04:22,551 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-10-02 16:04:22,551 - werkzeug - INFO -  * Running on http://10.104.51.226:9000/ (Press CTRL+C to quit)
2021-10-02 16:04:28,017 - job_service_app - INFO - JSON Request: {'clientname': 'Dina', 'jobprofile': 'Staff2', 'jobrequirements': 'Java Cloud'}
2021-10-02 16:04:28,017 - job_service_app - INFO - clientname: Dina
2021-10-02 16:04:28,017 - job_service_app - INFO - Going to call add job API...
2021-10-02 16:04:28,017 - job_service - INFO - In Add Job API
2021-10-02 16:04:28,017 - job_service - INFO - clientname Dina jobprofile Staff2 jobrequirements Java Cloud
2021-10-02 16:04:28,036 - job_service_app - ERROR - Exception on /jobservice/addjob [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-job-service/job_service_app.py", line 31, in add_candidate
    jobAdded =  job_service.addJob(clientname=clientname, jobprofile=jobprofile, jobrequirements=jobrequirements)
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-job-service/job_service.py", line 23, in addJob
    job_dao.addjobDAO(clientname, jobprofile, jobrequirements)
  File "/Users/dgnaneswaran/OneDrive - VMware, Inc/Dina/VM Materials/Take1/Cloud Architect Course works/Cloud Architect Final Project/Recruting-Agency/recruitment-job-service/job_dao.py", line 50, in addjobDAO
    cursor.execute(mySql_Add_Job_insert_Query)
AttributeError: 'NoneType' object has no attribute 'execute'
2021-10-02 16:04:28,039 - werkzeug - INFO - 127.0.0.1 - - [02/Oct/2021 16:04:28] "[35m[1mPOST /jobservice/addjob HTTP/1.1[0m" 500 -
